
### Docker Compose (optional, for local DB)
`docker-compose.yml`
```yaml
version: '1.0'
services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: chido
      POSTGRES_PASSWORD: ****************
      POSTGRES_DB: imperium
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
